### PR TITLE
Update images and add docker compose apps

### PR DESCRIPTION
**Pull request by eliotjordan**
This PR:

1. Simplifies and updates the docker images to use common base images for efficiency. 
2. Adds docker-compose based demo apps.
3. "Full" compose app spins up a complete stack including: solr, geoserver, iiif server, postgis database, and fully local sample data.

### CODE REVIEW

**Comment by eliotjordan** [comment]
@gravesm  @mejackreed  Let me know what you think about this. The full stack might be useful for workshops and demonstrations. 

If you decide to try it out, you should build the images rather than pull them from docker. The pre-built binaries on dockerhub aren't current until this PR is merged into master.

	$ ./scripts/build.sh

**Comment by gravesm** [comment]
:+1: I haven't done much with compose, yet, but being able to spin up a full stack for demo purposes seems like a great idea.

**Comment by mejackreed** [comment]
Yeah, I have no idea here... :+1: to whatever ya'll think is best. Anyway the fullstack can be pulled offline totally? On to a thumbdrive perhaps?

**Comment by eliotjordan** [comment]
The full-stack can be used offline, however the images need to pulled while online at some point. For portability, creating a vagrant vm with the images pre-loaded would be ideal.

**Comment by eliotjordan** [comment]
I am hoping to merge this PR so I can update the binaries on Docker Hub. Any objections?

**Comment by mejackreed** [comment]
No preference, happy with whatever you all decide

**Comment by gravesm** [comment]
Go for it.

**Pull request merged**
